[package]
name = "kernel"
version = "0.1.0"
authors = ["Philipp Oppermann <dev@phil-opp.com>", "Harald Hoyer <harald@redhat.com>"]
edition = "2018"

[[test]]
name = "should_panic"
harness = false

[[test]]
name = "stack_overflow"
harness = false

[dependencies]
vmbootspec = {version = "0", path = "../vmbootspec"}
vmsyscall = { version = "0", path = "../vmsyscall", features = ["no_std"]}

linux-syscall = { version="0.1", git = "https://github.com/enarx/enarx" }
linux-errno = { version="0.1", git = "https://github.com/enarx/enarx" }
crt0stack = { version = "0.2.1", git="https://github.com/haraldh/crt0stack", features = ["no_std"] }

xmas-elf = "0.7.0"
spin = "0.5.2"
x86_64 = "0.8.3"
pic8259_simple = "0.1.1"
uart_16550 = "0.2.1"
linked_list_allocator = "0.6.4"
serde_cbor = { version = "0.11", default-features = false }
serde = { version = "1.0", default-features = false, features = ["derive"] }
cstrptr = { version = "0.1", default-features = false, features = ["alloc", "unstable"] }
#safe-transmute = "0.10.1"

lazy_static = { version="1.4.0", features = ["spin_no_std"] }

[build-dependencies]
cc = "1.0.37"
llvm-tools = "0.1.1"
